import type { HeroSlide } from "./model.ts";

const PUBLISHED_FROM = "2000-01-01T00:00:00.000Z";

export const seedHeroSlides: HeroSlide[] = [
  {
    id: "hero-ritmo",
    eyebrow: "Beauty & Care Atelier · Padova",
    title: "La bellezza,",
    accent: "nel suo ritmo.",
    trailing: "",
    body: "Un atelier contemporaneo dedicato a capelli, pelle e benessere. Trattamenti su misura, gesti precisi e il tempo necessario per ascoltarti.",
    imageRef: "/images/rito/rito-hero-main.webp",
    imageAlt: "Professionista durante un trattamento viso in atelier",
    mobileImageRef: "",
    mobileImageAlt: "",
    primaryCta: { label: "Inizia la consulenza", target: "consultation" },
    secondaryCta: { label: "Scopri i trattamenti", target: "treatments" },
    status: "published",
    startsAt: PUBLISHED_FROM,
    endsAt: "",
    order: 0,
    version: 1,
  },
  {
    id: "hero-hair",
    eyebrow: "Hair · Forma · Movimento",
    title: "Il taglio segue,",
    accent: "la tua identità.",
    trailing: "",
    body: "Taglio, colore e texture costruiti con ascolto e precisione, per un risultato leggibile anche nella quotidianità.",
    imageRef: "/images/rito/rito-gallery-professional-01.webp",
    imageAlt: "Applicazione professionale del colore sui capelli",
    mobileImageRef: "",
    mobileImageAlt: "",
    primaryCta: { label: "Trova il tuo percorso", target: "consultation" },
    secondaryCta: { label: "Vedi i trattamenti", target: "treatments" },
    status: "published",
    startsAt: PUBLISHED_FROM,
    endsAt: "",
    order: 1,
    version: 1,
  },
  {
    id: "hero-skin",
    eyebrow: "Skin · Rituals · Care",
    title: "Prendersi cura,",
    accent: "senza fretta.",
    trailing: "",
    body: "Rituali essenziali per pelle e benessere, pensati per rallentare, ascoltare l'esigenza e scegliere solo ciò che serve.",
    imageRef: "/images/rito/rito-gallery-skin-01.webp",
    imageAlt: "Trattamento viso eseguito con un gesto delicato",
    mobileImageRef: "",
    mobileImageAlt: "",
    primaryCta: { label: "Inizia la consulenza", target: "consultation" },
    secondaryCta: { label: "Scopri lo studio", target: "studio" },
    status: "published",
    startsAt: PUBLISHED_FROM,
    endsAt: "",
    order: 2,
    version: 1,
  },
];
